---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ingress-ingress-k8s-io-v1-nginxingress
  failurePolicy: Fail
  name: mnginxingress.kb.io
  rules:
  - apiGroups:
    - ingress.ingress-k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nginxingresses
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ingress-ingress-k8s-io-v1-nginxingress
  failurePolicy: Fail
  name: vnginxingress.kb.io
  rules:
  - apiGroups:
    - ingress.ingress-k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nginxingresses
  sideEffects: None
