# permissions for end users to edit nginxingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nginxingress-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ingress-nginx-operator
    app.kubernetes.io/part-of: ingress-nginx-operator
    app.kubernetes.io/managed-by: kustomize
  name: nginxingress-editor-role
rules:
- apiGroups:
  - ingress.ingress-k8s.io
  resources:
  - nginxingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingress.ingress-k8s.io
  resources:
  - nginxingresses/status
  verbs:
  - get
