---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ingress.ingress-k8s.io
  resources:
  - nginxingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingress.ingress-k8s.io
  resources:
  - nginxingresses/finalizers
  verbs:
  - update
- apiGroups:
  - ingress.ingress-k8s.io
  resources:
  - nginxingresses/status
  verbs:
  - get
  - patch
  - update
