apiVersion: ingress.ingress-k8s.io/v1
kind: NginxIngress
metadata:
  annotations:
    ingress.nginx.k8s.io/lb-policy: "least_conn"
    ingress.nginx.k8s.io/lb-config: |
      {
        "svc-1": "max_fails=3 fail_timeout=30s weight=80",
        "svc-2": "max_fails=3 fail_timeout=30s weight=20",
        "svc-3": "backup"
      }
    ingress.nginx.k8s.io/enable-stream: "true"
    ingress.nginx.k8s.io/set-stream-config: |
      {
        "backends": [ {"name": "svc-1", "namespace": "web", "port": 8080}, {"name": "svc-2", "namespace": "api", "port": 8081} ]
      }
    ingress.nginx.k8s.io/allow-ip-list: "192.168.3.11,192.168.3.12"
    ingress.nginx.k8s.io/deny-ip-list: "192.168.3.11,192.168.3.12"
    ingress.nginx.k8s.io/enable-cos: "true"
    ingress.nginx.k8s.io/enable-limit-req: "true"
    ingress.nginx.k8s.io/set-limit-config: |
      {
        "limit_req_zone": "$binary_remote_addr$request_uri zone=per_ip_uri:10m rate=5r/s",
        "limit_req": "limit_req zone=per_ip_uri burst=5 nodelay;"
      }
    ingress.nginx.k8s.io/rewrite-target: "/$2"
    ingress.nginx.k8s.io/rewrite-flag: "break"
    ingress.nginx.k8s.io/use-proxy: "true"
    ingress.nginx.k8s.io/proxy-addr: |
      {
        "/api1": "https://api1.aaa.com",
        "/api2": "https://api2.aaa.com"
      }
  labels:
    app.kubernetes.io/name: nginxingress
    app.kubernetes.io/instance: nginxingress-sample
    app.kubernetes.io/part-of: ingress-nginx-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ingress-nginx-operator
  name: nginxingress-sample
spec:
# TODO(user): Add fields here