apiVersion: ingress.ingress-k8s.io/v1
kind: NginxIngress
metadata:
  annotations:

    ingress.nginx.k8s.io/lb-policy: "least_conn"
    ingress.nginx.k8s.io/use-lb: "true"
    ingress.nginx.k8s.io/use-weight: |
      {
        "svc-1": 80,
        "svc-2": 90
      }
  labels:
    app.kubernetes.io/name: nginxingress
    app.kubernetes.io/instance: nginxingress-sample
    app.kubernetes.io/part-of: ingress-nginx-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ingress-nginx-operator
  name: nginxingress-sample
spec:
# TODO(user): Add fields here